#!/bin/bash
#SBATCH --job-name="mnist"
#SBATCH -A givargis_lab

#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --error=%x.err
#SBATCH --out=%x.out

hn='hostname'
echo "Running job on host $hn"

echo "=== CPU Information ==="
lscpu
echo ""

echo ""
echo "=== GPU Information ==="
#nvidia-smi

echo -e "\n"

#module load cudasdk/22.9

make clean && make
./mnist

echo "=== Job Completed ==="
