/*
 * Auto Generated by The Gravity Compiler - Sat Mar  8 15:32:28 2025
 * Copyright (C) Tony Givargis, 2019-2020
 */

#ifndef _TEST_H_
#define _TEST_H_

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

int test_version(void);
size_t test_memory_size(void);
size_t test_memory_hard(void);
void test_initialize(void *m);
void *test_activate(void *m, const void *x);
void test_train(void *m, const void *x, const void *y);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _TEST_H_ */
