/*
 * Auto Generated by The Gravity Compiler - Sun Mar  9 16:22:19 2025
 * Copyright (C) Tony Givargis, 2019-2020
 */

#include <cuda_runtime.h>
#include <curand_kernel.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include "test.h"

/* _CUrandom_ */
__global__ void _CUrandom_(float *out, int inputLength, float param1, float param2) {
  int idx = blockIdx.x * blockDim.x + threadIdx.x;
  if (idx < inputLength) {
    curandState state;
    curand_init(10, idx, 0, &state);
    float r = curand_uniform(&state);
    out[idx] = param1 + r * param2;
  }
}

/* _CUMAC1_ */
__global__ void _CUMAC1_(float *z, float *A, float *B, int num_output, int num_input) {
  int idx = blockIdx.x * blockDim.x + threadIdx.x;
  if (idx < num_output) {
    float sum = 0.0f;
    for (int j = 0; j < num_input; j++) {
      sum += A[idx * num_input + j] * B[j];
    }
    z[idx] = sum;
  }
}

/* _CUADD_ */
__global__ void _CUADD_(float *za, float *B, int n) {
  int i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i < n) {
    za[i] += B[i];
  }
}

static void _initialize_(char *m_) {
  { /* RANDOM */
    float *z = (float *)( m_ + 0 );
    uint32_t size = 78400*sizeof(float);
    float *deviceOutput;
    cudaMalloc((void**) &deviceOutput, size);
    dim3 DimGrid((78400+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUrandom_<<<DimGrid, DimBlock>>>(deviceOutput, 78400, -0.006787, 0.013575);
    cudaDeviceSynchronize();
    cudaMemcpy(z, deviceOutput, size, cudaMemcpyDeviceToHost);
    cudaFree(deviceOutput);
  }

  { /* CLEAR */
    memset(m_ + 313600, 0, 100 * sizeof (float));
  }

  { /* RANDOM */
    float *z = (float *)( m_ + 314000 );
    uint32_t size = 10000*sizeof(float);
    float *deviceOutput;
    cudaMalloc((void**) &deviceOutput, size);
    dim3 DimGrid((10000+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUrandom_<<<DimGrid, DimBlock>>>(deviceOutput, 10000, -0.030000, 0.060000);
    cudaDeviceSynchronize();
    cudaMemcpy(z, deviceOutput, size, cudaMemcpyDeviceToHost);
    cudaFree(deviceOutput);
  }

  { /* CLEAR */
    memset(m_ + 354000, 0, 100 * sizeof (float));
  }

  { /* RANDOM */
    float *z = (float *)( m_ + 354400 );
    uint32_t size = 1000*sizeof(float);
    float *deviceOutput;
    cudaMalloc((void**) &deviceOutput, size);
    dim3 DimGrid((1000+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUrandom_<<<DimGrid, DimBlock>>>(deviceOutput, 1000, -0.054545, 0.109091);
    cudaDeviceSynchronize();
    cudaMemcpy(z, deviceOutput, size, cudaMemcpyDeviceToHost);
    cudaFree(deviceOutput);
  }

  { /* CLEAR */
    memset(m_ + 358400, 0, 10 * sizeof (float));
  }

  { /* RET */
    return;
  }
}

static float *_activate_(char *m_, const float *x_) {
  { /* COPYX */
    memcpy(m_ + 716880, x_, 784 * sizeof (float));
  }

  { /* cuMAC1 */
    float *z = (float *)( m_ + 720016 );
    const float *hostA = (const float *)( m_ + 0 );
    const float *hostB = (const float *)( m_ + 716880 );
    int size_A = 100 * 784 * sizeof(float);
    int size_B = 784 * sizeof(float);
    int size_z = 100 * sizeof(float);
    float *deviceA;
    float *deviceB;
    float *deviceOutput;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMalloc((void**) &deviceOutput, size_z);
    cudaMemcpy(deviceA, hostA, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, hostB, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((100+255)/256,1,1);
    dim3 DimBlock(256, 1,1);
    _CUMAC1_<<<DimGrid, DimBlock>>>(deviceOutput, deviceA, deviceB, 100, 784);
    cudaDeviceSynchronize();
    cudaMemcpy(z, deviceOutput, size_z, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
    cudaFree(deviceOutput);
  }

  { /* CUADD */
    float *za = (float *)( m_ + 720016 );
    const float *B = (const float *)( m_ + 313600 );
    int size_A = 100 * sizeof(float);
    int size_B = 100 * sizeof(float);
    float *deviceA;
    float *deviceB;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMemcpy(deviceA, za, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, B, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((100+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUADD_<<<DimGrid, DimBlock>>>(deviceA, deviceB, 100);
    cudaDeviceSynchronize();
    cudaMemcpy(za, deviceA, size_A, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
  }

  { /* RELU */
    float *za = (float *)( m_ + 720016 );
    uint32_t i;
    for (i=0; i<100; ++i) {
      if (0.0 >= za[i]) {
        za[i] = 0.0;
      }
    }
  }

  { /* cuMAC1 */
    float *z = (float *)( m_ + 720816 );
    const float *hostA = (const float *)( m_ + 314000 );
    const float *hostB = (const float *)( m_ + 720016 );
    int size_A = 100 * 100 * sizeof(float);
    int size_B = 100 * sizeof(float);
    int size_z = 100 * sizeof(float);
    float *deviceA;
    float *deviceB;
    float *deviceOutput;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMalloc((void**) &deviceOutput, size_z);
    cudaMemcpy(deviceA, hostA, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, hostB, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((100+255)/256,1,1);
    dim3 DimBlock(256, 1,1);
    _CUMAC1_<<<DimGrid, DimBlock>>>(deviceOutput, deviceA, deviceB, 100, 100);
    cudaDeviceSynchronize();
    cudaMemcpy(z, deviceOutput, size_z, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
    cudaFree(deviceOutput);
  }

  { /* CUADD */
    float *za = (float *)( m_ + 720816 );
    const float *B = (const float *)( m_ + 354000 );
    int size_A = 100 * sizeof(float);
    int size_B = 100 * sizeof(float);
    float *deviceA;
    float *deviceB;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMemcpy(deviceA, za, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, B, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((100+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUADD_<<<DimGrid, DimBlock>>>(deviceA, deviceB, 100);
    cudaDeviceSynchronize();
    cudaMemcpy(za, deviceA, size_A, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
  }

  { /* RELU */
    float *za = (float *)( m_ + 720816 );
    uint32_t i;
    for (i=0; i<100; ++i) {
      if (0.0 >= za[i]) {
        za[i] = 0.0;
      }
    }
  }

  { /* cuMAC1 */
    float *z = (float *)( m_ + 721616 );
    const float *hostA = (const float *)( m_ + 354400 );
    const float *hostB = (const float *)( m_ + 720816 );
    int size_A = 10 * 100 * sizeof(float);
    int size_B = 100 * sizeof(float);
    int size_z = 10 * sizeof(float);
    float *deviceA;
    float *deviceB;
    float *deviceOutput;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMalloc((void**) &deviceOutput, size_z);
    cudaMemcpy(deviceA, hostA, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, hostB, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((10+255)/256,1,1);
    dim3 DimBlock(256, 1,1);
    _CUMAC1_<<<DimGrid, DimBlock>>>(deviceOutput, deviceA, deviceB, 10, 100);
    cudaDeviceSynchronize();
    cudaMemcpy(z, deviceOutput, size_z, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
    cudaFree(deviceOutput);
  }

  { /* CUADD */
    float *za = (float *)( m_ + 721616 );
    const float *B = (const float *)( m_ + 358400 );
    int size_A = 10 * sizeof(float);
    int size_B = 10 * sizeof(float);
    float *deviceA;
    float *deviceB;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMemcpy(deviceA, za, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, B, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((10+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUADD_<<<DimGrid, DimBlock>>>(deviceA, deviceB, 10);
    cudaDeviceSynchronize();
    cudaMemcpy(za, deviceA, size_A, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
  }

  { /* SOFTMAX */
    float *za = (float *)( m_ + 721616 );
    float max=za[0], sum=0.0;
    uint32_t i;
    for (i=1; i<10; ++i) {
      if (max < za[i]) {
        max = za[i];
      }
    }
    for (i=0; i<10; ++i) {
      za[i] -= max;
      sum += (float)exp(za[i]);
    }
    for (i=0; i<10; ++i) {
      za[i] = (float)exp(za[i]) / sum;
    }
  }

  { /* RETARG */
    return (float *)( m_ + 721616 );
  }
}

static void _backprop_(char *m_, const float *y_) {
  { /* SUBY */
    float *z = (float *)( m_ + 721656 );
    const float *A = (const float *)( m_ + 721616 );
    uint32_t i;
    for (i=0; i<10; ++i) {
      z[i] = A[i] - y_[i];
    }
  }

  { /* MAC2 */
    float *z = (float *)( m_ + 721216 );
    const float *A = (const float *)( m_ + 354400 );
    const float *B = (const float *)( m_ + 721656 );
    uint32_t i, j;
    for (i=0; i<100; ++i) {
      z[i] = 0.0;
      for (j=0; j<10; ++j) {
        z[i] += A[j * 100 + i] * B[j];
      }
    }
  }

  { /* RELUD */
    float *za = (float *)( m_ + 721216 );
    const float *B = (const float *)( m_ + 720816 );
    uint32_t i;
    for (i=0; i<100; ++i) {
      if (0.0 >= B[i]) {
        za[i] = 0.0;
      }
    }
  }

  { /* MAC2 */
    float *z = (float *)( m_ + 720416 );
    const float *A = (const float *)( m_ + 314000 );
    const float *B = (const float *)( m_ + 721216 );
    uint32_t i, j;
    for (i=0; i<100; ++i) {
      z[i] = 0.0;
      for (j=0; j<100; ++j) {
        z[i] += A[j * 100 + i] * B[j];
      }
    }
  }

  { /* RELUD */
    float *za = (float *)( m_ + 720416 );
    const float *B = (const float *)( m_ + 720016 );
    uint32_t i;
    for (i=0; i<100; ++i) {
      if (0.0 >= B[i]) {
        za[i] = 0.0;
      }
    }
  }

  { /* CUADD */
    float *za = (float *)( m_ + 672040 );
    const float *B = (const float *)( m_ + 720416 );
    int size_A = 100 * sizeof(float);
    int size_B = 100 * sizeof(float);
    float *deviceA;
    float *deviceB;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMemcpy(deviceA, za, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, B, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((100+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUADD_<<<DimGrid, DimBlock>>>(deviceA, deviceB, 100);
    cudaDeviceSynchronize();
    cudaMemcpy(za, deviceA, size_A, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
  }

  { /* MAC3 */
    float *za = (float *)( m_ + 358440 );
    const float *B = (const float *)( m_ + 720416 );
    const float *C = (const float *)( m_ + 716880 );
    uint32_t i, j;
    for (i=0; i<100; ++i) {
      for (j=0; j<784; ++j) {
        za[i * 784 + j] += B[i] * C[j];
      }
    }
  }

  { /* CUADD */
    float *za = (float *)( m_ + 712440 );
    const float *B = (const float *)( m_ + 721216 );
    int size_A = 100 * sizeof(float);
    int size_B = 100 * sizeof(float);
    float *deviceA;
    float *deviceB;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMemcpy(deviceA, za, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, B, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((100+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUADD_<<<DimGrid, DimBlock>>>(deviceA, deviceB, 100);
    cudaDeviceSynchronize();
    cudaMemcpy(za, deviceA, size_A, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
  }

  { /* MAC3 */
    float *za = (float *)( m_ + 672440 );
    const float *B = (const float *)( m_ + 721216 );
    const float *C = (const float *)( m_ + 720016 );
    uint32_t i, j;
    for (i=0; i<100; ++i) {
      for (j=0; j<100; ++j) {
        za[i * 100 + j] += B[i] * C[j];
      }
    }
  }

  { /* CUADD */
    float *za = (float *)( m_ + 716840 );
    const float *B = (const float *)( m_ + 721656 );
    int size_A = 10 * sizeof(float);
    int size_B = 10 * sizeof(float);
    float *deviceA;
    float *deviceB;
    cudaMalloc((void**) &deviceA, size_A);
    cudaMalloc((void**) &deviceB, size_B);
    cudaMemcpy(deviceA, za, size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(deviceB, B, size_B, cudaMemcpyHostToDevice);
    dim3 DimGrid((10+255)/256,1,1);
    dim3 DimBlock(256,1,1);
    _CUADD_<<<DimGrid, DimBlock>>>(deviceA, deviceB, 10);
    cudaDeviceSynchronize();
    cudaMemcpy(za, deviceA, size_A, cudaMemcpyDeviceToHost);
    cudaFree(deviceA);
    cudaFree(deviceB);
  }

  { /* MAC3 */
    float *za = (float *)( m_ + 712840 );
    const float *B = (const float *)( m_ + 721656 );
    const float *C = (const float *)( m_ + 720816 );
    uint32_t i, j;
    for (i=0; i<10; ++i) {
      for (j=0; j<100; ++j) {
        za[i * 100 + j] += B[i] * C[j];
      }
    }
  }

  { /* RET */
    return;
  }
}

static void _train_(char *m_, const float *x_, const float *y_) {
  { /* CLEAR */
    memset(m_ + 358440, 0, 89610 * sizeof (float));
  }

  { /* BATCHLOOP */
    uint32_t i;
    for (i=0; i<8; ++i) {
        _activate_(m_, x_ + i * 784);
        _backprop_(m_, y_ + i * 10);
    }
  }

  { /* MAC4 */
    float *za = (float *)( m_ + 0 );
    const float *B = (const float *)( m_ + 358440 );
    uint32_t i;
    for (i=0; i<78400; ++i) {
      za[i] += B[i] * -0.012500;
    }
  }

  { /* MAC4 */
    float *za = (float *)( m_ + 313600 );
    const float *B = (const float *)( m_ + 672040 );
    uint32_t i;
    for (i=0; i<100; ++i) {
      za[i] += B[i] * -0.012500;
    }
  }

  { /* MAC4 */
    float *za = (float *)( m_ + 314000 );
    const float *B = (const float *)( m_ + 672440 );
    uint32_t i;
    for (i=0; i<10000; ++i) {
      za[i] += B[i] * -0.012500;
    }
  }

  { /* MAC4 */
    float *za = (float *)( m_ + 354000 );
    const float *B = (const float *)( m_ + 712440 );
    uint32_t i;
    for (i=0; i<100; ++i) {
      za[i] += B[i] * -0.012500;
    }
  }

  { /* MAC4 */
    float *za = (float *)( m_ + 354400 );
    const float *B = (const float *)( m_ + 712840 );
    uint32_t i;
    for (i=0; i<1000; ++i) {
      za[i] += B[i] * -0.012500;
    }
  }

  { /* MAC4 */
    float *za = (float *)( m_ + 358400 );
    const float *B = (const float *)( m_ + 716840 );
    uint32_t i;
    for (i=0; i<10; ++i) {
      za[i] += B[i] * -0.012500;
    }
  }

  { /* RET */
    return;
  }
}

int test_version(void) {
  return 10;
}

size_t test_memory_size(void) {
  return 721696;
}

size_t test_memory_hard(void) {
  return 358440;
}

void test_initialize(void *m) {
  _initialize_((char *)m);
}

void *test_activate(void *m, const void *x) {
  return _activate_((char *)m, (const float *)x);
}

void test_train(void *m, const void *x, const void *y) {
  _train_((char *)m, (const float *)x, (const float *)y);
}

